"""empty message

Revision ID: 6356e03b907d
Revises: 1b4ce668e47d
Create Date: 2019-10-24 16:22:24.278488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6356e03b907d'
down_revision = '1b4ce668e47d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
